register_discount:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: pweb_amano
          entity:
            domain: sensor
    car_no:
      required: true
      example: "12가3456"
      selector:
        text:
    discount_type:
      required: true
      example: "1"
      selector:
        select:
          custom_value: true
          options:
            - value: "1"
              label: "[무료] 1시간 할인"
            - value: "6"
              label: "[유료] 1시간 할인 (₩3,000)"
    memo:
      required: false
      selector:
        text:
    entry_date:
      required: false
      selector:
        date:

list_unregistered_vehicles:
  fields:
    device_id:
      required: true
      selector:
        device:
          integration: pweb_amano
          entity:
            domain: sensor
    days:
      required: false
      example: 2
      selector:
        number:
          min: 1
          max: 7
          mode: box
